apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secure-api
  namespace: argocd  # ArgoCD watches apps in this namespace
spec:
  project: default
  source:
    repoURL: https://github.com/<your-username>/eks-secure-docker-image
    targetRevision: main
    path: helm/secure-api
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: secure-api
  syncPolicy:
    automated:
      prune: true        # Delete removed resources
      selfHeal: true     # Auto-reconcile drift
    syncOptions:
      - CreateNamespace=true
