name: Build and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Extract Git metadata
      id: meta
      run: |
        echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        tags: |
          ${{ secrets.ECR_REGISTRY }}/secure-image:${{ steps.meta.outputs.sha }}
          ${{ secrets.ECR_REGISTRY }}/secure-image:${{ steps.meta.outputs.branch }}
        cache-from: type=registry,ref=${{ secrets.ECR_REGISTRY }}/secure-image:buildcache
        cache-to: type=registry,ref=${{ secrets.ECR_REGISTRY }}/secure-image:buildcache,mode=max

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@v0.13.1
      with:
        image-ref: ${{ secrets.ECR_REGISTRY }}/secure-image:${{ steps.meta.outputs.sha }}
        format: table
        severity: HIGH,CRITICAL
        ignore-unfixed: true
